#!/usr/bin/perl
eval 'exec /usr/bin/perl -S $0 ${1+"$@"}'
    if $running_under_some_shell;
			# this emulates #! processing on NIH machines.
			# (remove #! line above if indigestible)

eval '$'.$1.'$2;' while $ARGV[0] =~ /^([A-Za-z_0-9]+=)(.*)/ && shift;
			# process any FOO=bar switches

while (<>) {
    @Fld = split(' ', $_, -1);
    print "$ARGV\n" if $Fld[(1)-1] eq 'o' && $Fld[(5)-1] & 16;
}
